/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/google-font-display */
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import Header from '@/components/header';
import SideBar from '@/components/sidebar';
import StoreProvider from '../StoreProvider';
import { useAppDispatch, useAppSelector } from '@/lib/hooks';
import Payload from '@/components/payload';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'YouTube Music',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko' className='h-screen'>
      <head>
        <link
          href='https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200'
          rel='stylesheet'
        />
      </head>
      <body className={`h-full ${inter.className}`}>
        <StoreProvider>
          <Header />
          <div className='h-full flex flex-row'>
            <SideBar />
            <div className='pt-28 pl-44 w-full'>{children}</div>
          </div>
          <Payload />
        </StoreProvider>
      </body>
    </html>
  );
}
